# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """$username\t$directory
$character"""

# Change the default prompt characters
[character]
success_symbol = "  [   ](white bold)"
error_symbol = "  [   ](black bold)"

[username]
style_user = "green bold"
style_root = "red bold"
format = " [ $user ]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 3
truncation_symbol = ""
home_symbol = " ~"
read_only_style = "black bold"
read_only = " "
format = "[ $path]($style)[$read_only]($read_only_style)"
